# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b915c61d3172a9df24aa859b14c3dca1e7aefed4785cdc739af6aa0c50128ec5753d90626bc23250e92693b04b6fd6e2c8576cad3d4811e5849f89b88f98ddd8

test:
  secret_key_base: 5eeb83785087879db1da581b51e9d15b8e47c374c1e8a867d82caf7111806f5fb1479167ea97b682d20054493ee1d69ea2a858564387e2e5923f41357977ceae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
